version: "3.8"

x-airflow-common: &airflow-common
  image: apache/airflow:3.1.3
  environment:
    &airflow-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: "uQ3_1QLqVY4N7zuw7UvSX5N5GkQ__oBp5WeULGXjIQ8="
    AIRFLOW__CORE__LOAD_EXAMPLES: "True"
    _PIP_ADDITIONAL_REQUIREMENTS: ""
  volumes:
    - ./dags:/opt/airflow/dags
    - airflow-logs:/opt/airflow/logs
    - airflow-config:/opt/airflow/config
  depends_on:
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy
  networks:
    - airflow-poc

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - airflow-poc

  redis:
    image: redis:7
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
    networks:
      - airflow-poc

  airflow-init:
    <<: *airflow-common
    command: ["bash", "-c", "\
      airflow db migrate && \
      airflow users create \
        --username admin \
        --firstname Airflow \
        --lastname Admin \
        --role Admin \
        --email admin@example.com \
        --password admin && \
      airflow connections create-defaults"]
    environment:
      <<: *airflow-env
      AIRFLOW_UID: ${AIRFLOW_UID:-50000}
    user: "${AIRFLOW_UID:-50000}:0"
    profiles:
      - setup
    restart: on-failure

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    environment:
      <<: *airflow-env
      AIRFLOW_UID: ${AIRFLOW_UID:-50000}
    user: "${AIRFLOW_UID:-50000}:0"
    ports:
      - "8080:8080"
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    restart: unless-stopped

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    environment:
      <<: *airflow-env
      AIRFLOW_UID: ${AIRFLOW_UID:-50000}
    user: "${AIRFLOW_UID:-50000}:0"
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    restart: unless-stopped

networks:
  airflow-poc:

volumes:
  airflow-logs:
  airflow-config:
  postgres-data:
